version: '3.8'

services:
  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ecommerce-frontend
    environment:
      - NEXT_PUBLIC_DOTNET_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_SPRING_API_URL=http://localhost:8081/api/v1
      - NEXT_PUBLIC_ENVIRONMENT=production
    ports:
      - "3000:3000"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
