import {
  Product,
  Category,
  SubCategory,
  Campaign,
  Review,
  ProductReviewSummary,
} from "@/types";

// Mock Products
export const mockProducts: Product[] = [
  {
    id: 1,
    productName: "Premium Laptop",
    unitPrice: 25000,
    unitInStock: 15,
    quantityPerUnit: "1 adet",
    category: { id: 1, categoryName: "Elektronik", isActive: true },
    description:
      "Yüksek performanslı laptop - Intel i7 işlemci, 16GB RAM, 512GB SSD",
    imageUrl: "https://picsum.photos/600/400?random=1",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    productName: "Wireless Headphones",
    unitPrice: 1200,
    unitInStock: 50,
    quantityPerUnit: "1 adet",
    category: { id: 1, categoryName: "Elektronik", isActive: true },
    description: "Bluetooth kulaklık - 30 saat pil ömrü, gürültü engelleme",
    imageUrl: "https://picsum.photos/600/400?random=2",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    productName: "Smartphone",
    unitPrice: 18000,
    unitInStock: 25,
    quantityPerUnit: "1 adet",
    category: { id: 1, categoryName: "Elektronik", isActive: true },
    description: "Son model akıllı telefon - 128GB depolama, çift kamera",
    imageUrl: "https://picsum.photos/600/400?random=3",
    discount: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    productName: "Gaming Mouse",
    unitPrice: 800,
    unitInStock: 100,
    quantityPerUnit: "1 adet",
    category: { id: 1, categoryName: "Elektronik", isActive: true },
    description: "Profesyonel oyun faresi - 16000 DPI, RGB aydınlatma",
    imageUrl: "https://picsum.photos/600/400?random=4",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    productName: "Mechanical Keyboard",
    unitPrice: 1500,
    unitInStock: 75,
    quantityPerUnit: "1 adet",
    category: { id: 1, categoryName: "Elektronik", isActive: true },
    description: "Mekanik klavye - Cherry MX switches, RGB aydınlatma",
    imageUrl: "https://picsum.photos/600/400?random=5",
    discount: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    productName: 'Monitor 27"',
    unitPrice: 3500,
    unitInStock: 30,
    quantityPerUnit: "1 adet",
    category: { id: 1, categoryName: "Elektronik", isActive: true },
    description: "4K monitör - 27 inç, 144Hz yenileme hızı",
    imageUrl: "https://picsum.photos/600/400?random=6",
    discount: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    productName: "Tablet",
    unitPrice: 8000,
    unitInStock: 40,
    quantityPerUnit: "1 adet",
    category: { id: 1, categoryName: "Elektronik", isActive: true },
    description: "10 inç tablet - 64GB depolama, Wi-Fi + 4G",
    imageUrl: "https://picsum.photos/600/400?random=7",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: 1,
    categoryName: "Elektronik",
    description: "Telefon, bilgisayar, tablet ve diğer elektronik ürünler",
    imageUrl: "https://picsum.photos/300/200?random=10",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    categoryName: "Moda",
    description: "Giyim, ayakkabı, çanta ve aksesuar",
    imageUrl: "https://picsum.photos/300/200?random=11",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    categoryName: "Ev & Yaşam",
    description: "Ev dekorasyonu, mutfak, banyo ve yaşam ürünleri",
    imageUrl: "https://picsum.photos/300/200?random=12",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    categoryName: "Spor & Outdoor",
    description: "Spor giyim, fitness, outdoor ve kamp ürünleri",
    imageUrl: "https://picsum.photos/300/200?random=13",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    categoryName: "Anne & Bebek",
    description: "Bebek giyim, oyuncak, bakım ürünleri",
    imageUrl: "https://picsum.photos/300/200?random=14",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    categoryName: "Kozmetik & Kişisel Bakım",
    description: "Makyaj, cilt bakımı, parfüm ve kişisel bakım",
    imageUrl: "https://picsum.photos/300/200?random=15",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock SubCategories
export const mockSubCategories: SubCategory[] = [
  {
    id: 1,
    subCategoryName: "Laptop",
    description: "Dizüstü bilgisayarlar",
    categoryId: 1,
    categoryName: "Elektronik",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    subCategoryName: "Telefon",
    description: "Akıllı telefonlar",
    categoryId: 1,
    categoryName: "Elektronik",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    subCategoryName: "Aksesuar",
    description: "Telefon ve bilgisayar aksesuarları",
    categoryId: 1,
    categoryName: "Elektronik",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock Campaigns
export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    title: "Elektronik Ürünlerde Büyük İndirim",
    subtitle: "Tüm elektronik ürünlerde %30'a varan indirimler",
    description: "En sevilen elektronik ürünlerde sınırlı süre indirim fırsatı",
    discount: 30,
    imageUrl: "https://picsum.photos/800/400?random=20",
    backgroundColor: "bg-gradient-to-r from-blue-600 to-purple-600",
    timeLeft: "5 gün kaldı",
    buttonText: "Hemen Keşfet",
    buttonHref: "/categories/elektronik",
    isActive: true,
    startDate: new Date(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: "Moda Fırsatları",
    subtitle: "Yeni sezon koleksiyonunda %25 indirim",
    description: "En trend moda ürünlerinde özel fiyatlar",
    discount: 25,
    imageUrl: "https://picsum.photos/800/400?random=21",
    backgroundColor: "bg-gradient-to-r from-pink-600 to-red-600",
    timeLeft: "3 gün kaldı",
    buttonText: "Alışverişe Başla",
    buttonHref: "/categories/moda",
    isActive: true,
    startDate: new Date(),
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 1,
    productId: 1,
    userId: 1,
    userName: "Ahmet Yılmaz",
    rating: 5,
    comment: "Harika bir ürün! Kesinlikle tavsiye ederim.",
    isVerified: true,
    isHelpful: true,
    createdAt: "2024-01-15T00:00:00.000Z",
    updatedAt: "2024-01-15T00:00:00.000Z",
  },
  {
    id: 2,
    productId: 1,
    userId: 2,
    userName: "Ayşe Demir",
    rating: 4,
    comment: "Güzel ürün, hızlı kargo. Teşekkürler.",
    isVerified: true,
    isHelpful: false,
    createdAt: "2024-01-20T00:00:00.000Z",
    updatedAt: "2024-01-20T00:00:00.000Z",
  },
  {
    id: 3,
    productId: 1,
    userId: 3,
    userName: "Mehmet Kaya",
    rating: 5,
    comment: "Mükemmel kalite, fiyatına göre çok iyi.",
    isVerified: true,
    isHelpful: true,
    createdAt: "2024-01-25T00:00:00.000Z",
    updatedAt: "2024-01-25T00:00:00.000Z",
  },
  {
    id: 4,
    productId: 2,
    userId: 4,
    userName: "Fatma Öz",
    rating: 3,
    comment: "Orta kalite, beklentilerimi tam karşılamadı.",
    isVerified: false,
    isHelpful: false,
    createdAt: "2024-01-18T00:00:00.000Z",
    updatedAt: "2024-01-18T00:00:00.000Z",
  },
  {
    id: 5,
    productId: 2,
    userId: 5,
    userName: "Ali Veli",
    rating: 4,
    comment: "İyi ürün, hızlı teslimat.",
    isVerified: true,
    isHelpful: true,
    createdAt: "2024-01-22T00:00:00.000Z",
    updatedAt: "2024-01-22T00:00:00.000Z",
  },
];

// Mock Review Summaries
export const mockReviewSummaries: ProductReviewSummary[] = [
  {
    productId: 1,
    averageRating: 4.7,
    totalReviews: 3,
    rating1Count: 0,
    rating2Count: 0,
    rating3Count: 0,
    rating4Count: 1,
    rating5Count: 2,
  },
  {
    productId: 2,
    averageRating: 3.5,
    totalReviews: 2,
    rating1Count: 0,
    rating2Count: 0,
    rating3Count: 1,
    rating4Count: 1,
    rating5Count: 0,
  },
  {
    productId: 3,
    averageRating: 5.0,
    totalReviews: 1,
    rating1Count: 0,
    rating2Count: 0,
    rating3Count: 0,
    rating4Count: 0,
    rating5Count: 1,
  },
  {
    productId: 4,
    averageRating: 4.0,
    totalReviews: 1,
    rating1Count: 0,
    rating2Count: 0,
    rating3Count: 0,
    rating4Count: 1,
    rating5Count: 0,
  },
  {
    productId: 5,
    averageRating: 5.0,
    totalReviews: 1,
    rating1Count: 0,
    rating2Count: 0,
    rating3Count: 0,
    rating4Count: 0,
    rating5Count: 1,
  },
  {
    productId: 6,
    averageRating: 3.0,
    totalReviews: 1,
    rating1Count: 0,
    rating2Count: 0,
    rating3Count: 1,
    rating4Count: 0,
    rating5Count: 0,
  },
  {
    productId: 7,
    averageRating: 4.0,
    totalReviews: 1,
    rating1Count: 0,
    rating2Count: 0,
    rating3Count: 0,
    rating4Count: 1,
    rating5Count: 0,
  },
];
