import { Product, Category, SubCategory, Campaign, Review, ProductReviewSummary } from "@/types";

export const mockCategories: Category[] = [
  {
    id: 1,
    categoryName: "Elektronik",
    description: "Telefon, bilgisayar, tablet ve diğer elektronik ürünler",
    isActive: true,
  },
  {
    id: 2,
    categoryName: "Moda",
    description: "Giyim, ayakkabı, çanta ve aksesuar",
    isActive: true,
  },
  {
    id: 3,
    categoryName: "Ev & Yaşam",
    description: "Ev dekorasyonu, mutfak, banyo ve yaşam ürünleri",
    isActive: true,
  },
  {
    id: 4,
    categoryName: "Spor & Outdoor",
    description: "Spor giyim, fitness, outdoor ve kamp ürünleri",
    isActive: true,
  },
  {
    id: 5,
    categoryName: "Anne & Bebek",
    description: "Bebek giyim, oyuncak, bakım ürünleri",
    isActive: true,
  },
  {
    id: 6,
    categoryName: "Kozmetik & Kişisel Bakım",
    description: "Makyaj, cilt bakımı, parfüm ve kişisel bakım",
    isActive: true,
  },
  {
    id: 7,
    categoryName: "Süpermarket",
    description: "Gıda, temizlik, kişisel bakım ürünleri",
    isActive: true,
  },
  {
    id: 8,
    categoryName: "Kitap & Müzik",
    description: "Kitaplar, müzik, film ve hobi ürünleri",
    isActive: true,
  },
  {
    id: 9,
    categoryName: "Oto & Bahçe",
    description: "Araç aksesuarları, bahçe malzemeleri",
    isActive: true,
  },
  {
    id: 10,
    categoryName: "Kırtasiye & Ofis",
    description: "Ofis malzemeleri, kırtasiye ürünleri",
    isActive: true,
  },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    productName: "Premium Laptop",
    unitPrice: 25000,
    unitInStock: 15,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description:
      "Yüksek performanslı laptop - Intel i7 işlemci, 16GB RAM, 512GB SSD",
    imageUrl: "https://picsum.photos/400/300?random=1",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    productName: "Wireless Headphones",
    unitPrice: 1200,
    unitInStock: 50,
    quantityPerUnit: "1 çift",
    category: mockCategories[0],
    description: "Bluetooth kablosuz kulaklık - 30 saat pil ömrü",
    imageUrl: "https://picsum.photos/400/300?random=2",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    productName: "Smartphone",
    unitPrice: 15000,
    unitInStock: 25,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "Son teknoloji akıllı telefon",
    imageUrl: "https://picsum.photos/400/300?random=3",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    productName: "Gaming Mouse",
    unitPrice: 450,
    unitInStock: 40,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "Profesyonel oyun faresi - RGB aydınlatma",
    imageUrl: "https://picsum.photos/400/300?random=7",
    discount: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    productName: "Mechanical Keyboard",
    unitPrice: 800,
    unitInStock: 35,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "Mekanik klavye - Cherry MX switch",
    imageUrl: "https://picsum.photos/400/300?random=8",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    productName: "4K Monitor",
    unitPrice: 3500,
    unitInStock: 20,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "27 inç 4K monitör - HDR desteği",
    imageUrl: "https://picsum.photos/400/300?random=9",
    discount: 25,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    productName: "Tablet",
    unitPrice: 4500,
    unitInStock: 18,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "10.1 inç tablet - 128GB depolama",
    imageUrl: "https://picsum.photos/400/300?random=10",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    productName: "Running Shoes",
    unitPrice: 800,
    unitInStock: 30,
    quantityPerUnit: "1 çift",
    category: mockCategories[3],
    description: "Rahat koşu ayakkabısı",
    imageUrl: "https://picsum.photos/400/300?random=4",
    discount: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    productName: "Yoga Mat",
    unitPrice: 200,
    unitInStock: 60,
    quantityPerUnit: "1 adet",
    category: mockCategories[3],
    description: "Anti-slip yoga matı - 6mm kalınlık",
    imageUrl: "https://picsum.photos/400/300?random=11",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    productName: "Dumbbell Set",
    unitPrice: 1200,
    unitInStock: 25,
    quantityPerUnit: "1 set",
    category: mockCategories[3],
    description: "Ayarlanabilir dambıl seti - 2x20kg",
    imageUrl: "https://picsum.photos/400/300?random=12",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    productName: "Basketball",
    unitPrice: 150,
    unitInStock: 45,
    quantityPerUnit: "1 adet",
    category: mockCategories[3],
    description: "Resmi basketbol topu - Size 7",
    imageUrl: "https://picsum.photos/400/300?random=13",
    discount: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    productName: "Coffee Maker",
    unitPrice: 1500,
    unitInStock: 12,
    quantityPerUnit: "1 adet",
    category: mockCategories[2],
    description: "Otomatik kahve makinesi",
    imageUrl: "https://picsum.photos/400/300?random=5",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    productName: "Air Purifier",
    unitPrice: 2500,
    unitInStock: 15,
    quantityPerUnit: "1 adet",
    category: mockCategories[2],
    description: "HEPA filtreli hava temizleyici",
    imageUrl: "https://picsum.photos/400/300?random=14",
    discount: 22,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    productName: "Smart Speaker",
    unitPrice: 800,
    unitInStock: 30,
    quantityPerUnit: "1 adet",
    category: mockCategories[2],
    description: "Akıllı hoparlör - Sesli asistan",
    imageUrl: "https://picsum.photos/400/300?random=15",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    productName: "LED Desk Lamp",
    unitPrice: 300,
    unitInStock: 50,
    quantityPerUnit: "1 adet",
    category: mockCategories[2],
    description: "Ayarlanabilir LED masa lambası",
    imageUrl: "https://picsum.photos/400/300?random=16",
    discount: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    productName: "Cotton T-Shirt",
    unitPrice: 300,
    unitInStock: 50,
    quantityPerUnit: "1 adet",
    category: mockCategories[1],
    description: "Pamuklu t-shirt",
    imageUrl: "https://picsum.photos/400/300?random=6",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    productName: "Denim Jacket",
    unitPrice: 1200,
    unitInStock: 25,
    quantityPerUnit: "1 adet",
    category: mockCategories[1],
    description: "Klasik denim ceket",
    imageUrl: "https://picsum.photos/400/300?random=17",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    productName: "Sneakers",
    unitPrice: 600,
    unitInStock: 40,
    quantityPerUnit: "1 çift",
    category: mockCategories[1],
    description: "Günlük kullanım spor ayakkabı",
    imageUrl: "https://picsum.photos/400/300?random=18",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    productName: "Leather Bag",
    unitPrice: 800,
    unitInStock: 20,
    quantityPerUnit: "1 adet",
    category: mockCategories[1],
    description: "Deri çanta - Laptop uyumlu",
    imageUrl: "https://picsum.photos/400/300?random=19",
    discount: 25,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    productName: "Baby Stroller",
    unitPrice: 2500,
    unitInStock: 12,
    quantityPerUnit: "1 adet",
    category: mockCategories[4],
    description: "Katlanabilir bebek arabası",
    imageUrl: "https://picsum.photos/400/300?random=20",
    discount: 30,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    productName: "Baby Monitor",
    unitPrice: 600,
    unitInStock: 18,
    quantityPerUnit: "1 adet",
    category: mockCategories[4],
    description: "Video bebek monitörü",
    imageUrl: "https://picsum.photos/400/300?random=21",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 22,
    productName: "Skincare Set",
    unitPrice: 400,
    unitInStock: 35,
    quantityPerUnit: "1 set",
    category: mockCategories[5],
    description: "Cilt bakım seti - 3 parça",
    imageUrl: "https://picsum.photos/400/300?random=22",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 23,
    productName: "Perfume",
    unitPrice: 800,
    unitInStock: 25,
    quantityPerUnit: "1 adet",
    category: mockCategories[5],
    description: "Erkek parfümü - 100ml",
    imageUrl: "https://picsum.photos/400/300?random=23",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 24,
    productName: "Organic Honey",
    unitPrice: 80,
    unitInStock: 100,
    quantityPerUnit: "500g",
    category: mockCategories[6],
    description: "Organik çiçek balı",
    imageUrl: "https://picsum.photos/400/300?random=24",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 25,
    productName: "Olive Oil",
    unitPrice: 120,
    unitInStock: 80,
    quantityPerUnit: "1L",
    category: mockCategories[6],
    description: "Sızma zeytinyağı",
    imageUrl: "https://picsum.photos/400/300?random=25",
    discount: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 26,
    productName: "Programming Book",
    unitPrice: 150,
    unitInStock: 60,
    quantityPerUnit: "1 adet",
    category: mockCategories[7],
    description: "JavaScript programlama kitabı",
    imageUrl: "https://picsum.photos/400/300?random=26",
    discount: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 27,
    productName: "Bluetooth Speaker",
    unitPrice: 350,
    unitInStock: 40,
    quantityPerUnit: "1 adet",
    category: mockCategories[7],
    description: "Taşınabilir Bluetooth hoparlör",
    imageUrl: "https://picsum.photos/400/300?random=27",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 28,
    productName: "Car Phone Mount",
    unitPrice: 200,
    unitInStock: 50,
    quantityPerUnit: "1 adet",
    category: mockCategories[8],
    description: "Araç telefon tutucu",
    imageUrl: "https://picsum.photos/400/300?random=28",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 29,
    productName: "Garden Tools Set",
    unitPrice: 400,
    unitInStock: 25,
    quantityPerUnit: "1 set",
    category: mockCategories[8],
    description: "Bahçe aletleri seti - 5 parça",
    imageUrl: "https://picsum.photos/400/300?random=29",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 30,
    productName: "Office Chair",
    unitPrice: 1800,
    unitInStock: 15,
    quantityPerUnit: "1 adet",
    category: mockCategories[9],
    description: "Ergonomik ofis koltuğu",
    imageUrl: "https://picsum.photos/400/300?random=30",
    discount: 25,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 31,
    productName: "Notebook Set",
    unitPrice: 50,
    unitInStock: 200,
    quantityPerUnit: "5 adet",
    category: mockCategories[9],
    description: "Spiral defter seti",
    imageUrl: "https://picsum.photos/400/300?random=31",
    discount: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    title: "PREMIUM İNDİRİM GÜNLERİ",
    subtitle: "6-13 EKİM",
    description: "Premium üyelere özel indirimler",
    discount: 50,
    imageUrl: "https://picsum.photos/200/150?random=1",
    backgroundColor: "bg-gradient-to-r from-purple-600 to-purple-800",
    timeLeft: "5 gün 12 saat",
    buttonText: "Alışverişe Başla",
    buttonHref: "/products?campaign=premium",
    isActive: true,
    startDate: new Date(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: "Teknoloji Ürünlerinde",
    subtitle: "PREMIUM'A ÖZEL",
    description: "Sepette 1.000 TL'ye Varan İndirimler",
    discount: 30,
    imageUrl: "https://picsum.photos/200/150?random=2",
    backgroundColor: "bg-gradient-to-r from-blue-600 to-blue-800",
    timeLeft: "3 gün 8 saat",
    buttonText: "Teknoloji Ürünleri",
    buttonHref: "/categories/elektronik",
    isActive: true,
    startDate: new Date(),
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: "Senin İçin Seçtiklerimiz",
    subtitle: "ÖZEL FIRSATLAR",
    description: "Size özel seçilmiş ürünlerde büyük indirimler",
    discount: 25,
    imageUrl: "https://picsum.photos/200/150?random=3",
    backgroundColor: "bg-gradient-to-r from-orange-500 to-red-500",
    timeLeft: "7 gün 15 saat",
    buttonText: "Keşfet",
    buttonHref: "/products?featured=true",
    isActive: true,
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockReviews: Review[] = [
  {
    id: 1,
    productId: 1,
    userId: 1,
    userName: "Ahmet Yılmaz",
    rating: 5,
    comment: "Harika bir ürün! Kesinlikle tavsiye ederim.",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: 2,
    productId: 1,
    userId: 2,
    userName: "Ayşe Demir",
    rating: 4,
    comment: "Güzel ürün, hızlı kargo. Teşekkürler.",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: 3,
    productId: 1,
    userId: 3,
    userName: "Mehmet Kaya",
    rating: 5,
    comment: "Mükemmel kalite, fiyatına göre çok iyi.",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: 4,
    productId: 2,
    userId: 4,
    userName: "Fatma Öz",
    rating: 3,
    comment: "Orta kalite, beklentilerimi tam karşılamadı.",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: 5,
    productId: 2,
    userId: 5,
    userName: "Ali Veli",
    rating: 4,
    comment: "İyi ürün, hızlı teslimat.",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: 6,
    productId: 3,
    userId: 6,
    userName: "Zeynep Ak",
    rating: 5,
    comment: "Çok memnun kaldım, tekrar alacağım.",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
  },
  {
    id: 7,
    productId: 4,
    userId: 7,
    userName: "Can Özkan",
    rating: 4,
    comment: "Güzel ürün, kaliteli malzeme.",
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-01-30"),
  },
  {
    id: 8,
    productId: 5,
    userId: 8,
    userName: "Elif Yıldız",
    rating: 5,
    comment: "Harika! Kesinlikle tavsiye ederim.",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: 9,
    productId: 6,
    userId: 9,
    userName: "Burak Kılıç",
    rating: 3,
    comment: "Orta kalite, fiyatına göre uygun.",
    createdAt: new Date("2024-02-02"),
    updatedAt: new Date("2024-02-02"),
  },
  {
    id: 10,
    productId: 7,
    userId: 10,
    userName: "Selin Arslan",
    rating: 4,
    comment: "İyi ürün, hızlı kargo.",
    createdAt: new Date("2024-02-03"),
    updatedAt: new Date("2024-02-03"),
  },
];

export const mockReviewSummaries: ProductReviewSummary[] = [
  {
    productId: 1,
    averageRating: 4.7,
    totalReviews: 3,
    ratingDistribution: {
      5: 2,
      4: 1,
      3: 0,
      2: 0,
      1: 0,
    },
  },
  {
    productId: 2,
    averageRating: 3.5,
    totalReviews: 2,
    ratingDistribution: {
      5: 0,
      4: 1,
      3: 1,
      2: 0,
      1: 0,
    },
  },
  {
    productId: 3,
    averageRating: 5.0,
    totalReviews: 1,
    ratingDistribution: {
      5: 1,
      4: 0,
      3: 0,
      2: 0,
      1: 0,
    },
  },
  {
    productId: 4,
    averageRating: 4.0,
    totalReviews: 1,
    ratingDistribution: {
      5: 0,
      4: 1,
      3: 0,
      2: 0,
      1: 0,
    },
  },
  {
    productId: 5,
    averageRating: 5.0,
    totalReviews: 1,
    ratingDistribution: {
      5: 1,
      4: 0,
      3: 0,
      2: 0,
      1: 0,
    },
  },
  {
    productId: 6,
    averageRating: 3.0,
    totalReviews: 1,
    ratingDistribution: {
      5: 0,
      4: 0,
      3: 1,
      2: 0,
      1: 0,
    },
  },
  {
    productId: 7,
    averageRating: 4.0,
    totalReviews: 1,
    ratingDistribution: {
      5: 0,
      4: 1,
      3: 0,
      2: 0,
      1: 0,
    },
  },
];

export const mockSubCategories: SubCategory[] = [
  // Elektronik SubCategories
  { id: 1, subCategoryName: "Telefon & Tablet", categoryId: 1, categoryName: "Elektronik", description: "Akıllı telefonlar ve tabletler", isActive: true },
  { id: 2, subCategoryName: "Bilgisayar", categoryId: 1, categoryName: "Elektronik", description: "Laptop, masaüstü bilgisayar ve aksesuarları", isActive: true },
  { id: 3, subCategoryName: "Ev Elektroniği", categoryId: 1, categoryName: "Elektronik", description: "TV, ses sistemleri ve ev elektroniği", isActive: true },
  
  // Moda SubCategories
  { id: 4, subCategoryName: "Kadın Giyim", categoryId: 2, categoryName: "Moda", description: "Kadın giyim ürünleri", isActive: true },
  { id: 5, subCategoryName: "Erkek Giyim", categoryId: 2, categoryName: "Moda", description: "Erkek giyim ürünleri", isActive: true },
  { id: 6, subCategoryName: "Ayakkabı & Çanta", categoryId: 2, categoryName: "Moda", description: "Ayakkabı ve çanta ürünleri", isActive: true },
  
  // Ev & Yaşam SubCategories
  { id: 7, subCategoryName: "Mobilya", categoryId: 3, categoryName: "Ev & Yaşam", description: "Ev mobilyaları", isActive: true },
  { id: 8, subCategoryName: "Dekorasyon", categoryId: 3, categoryName: "Ev & Yaşam", description: "Ev dekorasyon ürünleri", isActive: true },
  { id: 9, subCategoryName: "Mutfak & Banyo", categoryId: 3, categoryName: "Ev & Yaşam", description: "Mutfak ve banyo ürünleri", isActive: true },
  
  // Spor & Outdoor SubCategories
  { id: 10, subCategoryName: "Fitness", categoryId: 4, categoryName: "Spor & Outdoor", description: "Fitness ve spor ekipmanları", isActive: true },
  { id: 11, subCategoryName: "Outdoor", categoryId: 4, categoryName: "Spor & Outdoor", description: "Açık hava sporları", isActive: true },
  { id: 12, subCategoryName: "Takım Sporları", categoryId: 4, categoryName: "Spor & Outdoor", description: "Takım sporları ekipmanları", isActive: true },
  
  // Anne & Bebek SubCategories
  { id: 13, subCategoryName: "Bebek Giyim", categoryId: 5, categoryName: "Anne & Bebek", description: "Bebek giyim ürünleri", isActive: true },
  { id: 14, subCategoryName: "Bebek Bakım", categoryId: 5, categoryName: "Anne & Bebek", description: "Bebek bakım ürünleri", isActive: true },
  { id: 15, subCategoryName: "Bebek Beslenme", categoryId: 5, categoryName: "Anne & Bebek", description: "Bebek beslenme ürünleri", isActive: true },
  
  // Kozmetik & Kişisel Bakım SubCategories
  { id: 16, subCategoryName: "Makyaj", categoryId: 6, categoryName: "Kozmetik & Kişisel Bakım", description: "Makyaj ürünleri", isActive: true },
  { id: 17, subCategoryName: "Cilt Bakımı", categoryId: 6, categoryName: "Kozmetik & Kişisel Bakım", description: "Cilt bakım ürünleri", isActive: true },
  { id: 18, subCategoryName: "Saç Bakımı", categoryId: 6, categoryName: "Kozmetik & Kişisel Bakım", description: "Saç bakım ürünleri", isActive: true },
  
  // Süpermarket SubCategories
  { id: 19, subCategoryName: "Gıda", categoryId: 7, categoryName: "Süpermarket", description: "Gıda ürünleri", isActive: true },
  { id: 20, subCategoryName: "Temizlik", categoryId: 7, categoryName: "Süpermarket", description: "Temizlik ürünleri", isActive: true },
  { id: 21, subCategoryName: "Kişisel Bakım", categoryId: 7, categoryName: "Süpermarket", description: "Kişisel bakım ürünleri", isActive: true },
  
  // Kitap & Müzik SubCategories
  { id: 22, subCategoryName: "Kitaplar", categoryId: 8, categoryName: "Kitap & Müzik", description: "Kitap ürünleri", isActive: true },
  { id: 23, subCategoryName: "Müzik", categoryId: 8, categoryName: "Kitap & Müzik", description: "Müzik ürünleri", isActive: true },
  { id: 24, subCategoryName: "Medya", categoryId: 8, categoryName: "Kitap & Müzik", description: "Medya ürünleri", isActive: true },
  
  // Oto & Bahçe SubCategories
  { id: 25, subCategoryName: "Otomotiv", categoryId: 9, categoryName: "Oto & Bahçe", description: "Otomotiv ürünleri", isActive: true },
  { id: 26, subCategoryName: "Bahçe", categoryId: 9, categoryName: "Oto & Bahçe", description: "Bahçe ürünleri", isActive: true },
  { id: 27, subCategoryName: "İnşaat & Yapı", categoryId: 9, categoryName: "Oto & Bahçe", description: "İnşaat ve yapı ürünleri", isActive: true },
  
  // Kırtasiye & Ofis SubCategories
  { id: 28, subCategoryName: "Kırtasiye", categoryId: 10, categoryName: "Kırtasiye & Ofis", description: "Kırtasiye ürünleri", isActive: true },
  { id: 29, subCategoryName: "Ofis", categoryId: 10, categoryName: "Kırtasiye & Ofis", description: "Ofis ürünleri", isActive: true },
  { id: 30, subCategoryName: "Okul", categoryId: 10, categoryName: "Kırtasiye & Ofis", description: "Okul ürünleri", isActive: true },
];
