import { Product, Category, Campaign } from '@/types'

// Mock Categories
export const mockCategories: Category[] = [
  { id: 1, categoryName: "Elektronik", description: "Telefon, bilgisayar, tablet ve diğer elektronik ürünler", isActive: true },
  { id: 2, categoryName: "Moda", description: "Giyim, ayakkabı, çanta ve aksesuar", isActive: true },
  { id: 3, categoryName: "Ev & Yaşam", description: "Ev dekorasyonu, mutfak, banyo ve yaşam ürünleri", isActive: true },
  { id: 4, categoryName: "Spor & Outdoor", description: "Spor giyim, fitness, outdoor ve kamp ürünleri", isActive: true },
  { id: 5, categoryName: "Anne & Bebek", description: "Bebek giyim, oyuncak, bakım ürünleri", isActive: true },
  { id: 6, categoryName: "Kozmetik & Kişisel Bakım", description: "Makyaj, cilt bakımı, parfüm ve kişisel bakım", isActive: true },
  { id: 7, categoryName: "Süpermarket", description: "Gıda, temizlik, kişisel bakım ürünleri", isActive: true },
  { id: 8, categoryName: "Kitap & Müzik", description: "Kitaplar, müzik, film ve hobi ürünleri", isActive: true },
  { id: 9, categoryName: "Oto & Bahçe", description: "Araç aksesuarları, bahçe malzemeleri", isActive: true },
  { id: 10, categoryName: "Kırtasiye & Ofis", description: "Ofis malzemeleri, kırtasiye ürünleri", isActive: true }
]

// Mock Products
export const mockProducts: Product[] = [
  // Elektronik Ürünleri
  {
    id: 1,
    productName: "Premium Laptop",
    unitPrice: 25000,
    unitInStock: 15,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "Yüksek performanslı laptop - Intel i7 işlemci, 16GB RAM, 512GB SSD",
    imageUrl: "https://picsum.photos/400/300?random=1",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    productName: "Wireless Headphones",
    unitPrice: 1200,
    unitInStock: 50,
    quantityPerUnit: "1 çift",
    category: mockCategories[0],
    description: "Bluetooth kablosuz kulaklık - 30 saat pil ömrü",
    imageUrl: "https://picsum.photos/400/300?random=2",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    productName: "Smartphone",
    unitPrice: 15000,
    unitInStock: 25,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "Son teknoloji akıllı telefon",
    imageUrl: "https://picsum.photos/400/300?random=3",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    productName: "Gaming Mouse",
    unitPrice: 450,
    unitInStock: 40,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "Profesyonel oyun faresi - RGB aydınlatma",
    imageUrl: "https://picsum.photos/400/300?random=7",
    discount: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    productName: "Mechanical Keyboard",
    unitPrice: 800,
    unitInStock: 35,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "Mekanik klavye - Cherry MX switch",
    imageUrl: "https://picsum.photos/400/300?random=8",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    productName: "4K Monitor",
    unitPrice: 3500,
    unitInStock: 20,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "27 inç 4K monitör - HDR desteği",
    imageUrl: "https://picsum.photos/400/300?random=9",
    discount: 25,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    productName: "Tablet",
    unitPrice: 4500,
    unitInStock: 18,
    quantityPerUnit: "1 adet",
    category: mockCategories[0],
    description: "10.1 inç tablet - 128GB depolama",
    imageUrl: "https://picsum.photos/400/300?random=10",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Spor Ürünleri
  {
    id: 4,
    productName: "Running Shoes",
    unitPrice: 800,
    unitInStock: 30,
    quantityPerUnit: "1 çift",
    category: mockCategories[3],
    description: "Rahat koşu ayakkabısı",
    imageUrl: "https://picsum.photos/400/300?random=4",
    discount: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    productName: "Yoga Mat",
    unitPrice: 200,
    unitInStock: 60,
    quantityPerUnit: "1 adet",
    category: mockCategories[3],
    description: "Anti-slip yoga matı - 6mm kalınlık",
    imageUrl: "https://picsum.photos/400/300?random=11",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    productName: "Dumbbell Set",
    unitPrice: 1200,
    unitInStock: 25,
    quantityPerUnit: "1 set",
    category: mockCategories[3],
    description: "Ayarlanabilir dambıl seti - 2x20kg",
    imageUrl: "https://picsum.photos/400/300?random=12",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    productName: "Basketball",
    unitPrice: 150,
    unitInStock: 45,
    quantityPerUnit: "1 adet",
    category: mockCategories[3],
    description: "Resmi basketbol topu - Size 7",
    imageUrl: "https://picsum.photos/400/300?random=13",
    discount: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Ev & Yaşam Ürünleri
  {
    id: 5,
    productName: "Coffee Maker",
    unitPrice: 1500,
    unitInStock: 12,
    quantityPerUnit: "1 adet",
    category: mockCategories[2],
    description: "Otomatik kahve makinesi",
    imageUrl: "https://picsum.photos/400/300?random=5",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    productName: "Air Purifier",
    unitPrice: 2500,
    unitInStock: 15,
    quantityPerUnit: "1 adet",
    category: mockCategories[2],
    description: "HEPA filtreli hava temizleyici",
    imageUrl: "https://picsum.photos/400/300?random=14",
    discount: 22,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    productName: "Smart Speaker",
    unitPrice: 800,
    unitInStock: 30,
    quantityPerUnit: "1 adet",
    category: mockCategories[2],
    description: "Akıllı hoparlör - Sesli asistan",
    imageUrl: "https://picsum.photos/400/300?random=15",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    productName: "LED Desk Lamp",
    unitPrice: 300,
    unitInStock: 50,
    quantityPerUnit: "1 adet",
    category: mockCategories[2],
    description: "Ayarlanabilir LED masa lambası",
    imageUrl: "https://picsum.photos/400/300?random=16",
    discount: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Giyim Ürünleri
  {
    id: 6,
    productName: "Cotton T-Shirt",
    unitPrice: 300,
    unitInStock: 50,
    quantityPerUnit: "1 adet",
    category: mockCategories[1],
    description: "Pamuklu t-shirt",
    imageUrl: "https://picsum.photos/400/300?random=6",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    productName: "Denim Jacket",
    unitPrice: 1200,
    unitInStock: 25,
    quantityPerUnit: "1 adet",
    category: mockCategories[1],
    description: "Klasik denim ceket",
    imageUrl: "https://picsum.photos/400/300?random=17",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    productName: "Sneakers",
    unitPrice: 600,
    unitInStock: 40,
    quantityPerUnit: "1 çift",
    category: mockCategories[1],
    description: "Günlük kullanım spor ayakkabı",
    imageUrl: "https://picsum.photos/400/300?random=18",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    productName: "Leather Bag",
    unitPrice: 800,
    unitInStock: 20,
    quantityPerUnit: "1 adet",
    category: mockCategories[1],
    description: "Deri çanta - Laptop uyumlu",
    imageUrl: "https://picsum.photos/400/300?random=19",
    discount: 25,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Anne & Bebek Ürünleri
  {
    id: 20,
    productName: "Baby Stroller",
    unitPrice: 2500,
    unitInStock: 12,
    quantityPerUnit: "1 adet",
    category: mockCategories[4],
    description: "Katlanabilir bebek arabası",
    imageUrl: "https://picsum.photos/400/300?random=20",
    discount: 30,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    productName: "Baby Monitor",
    unitPrice: 600,
    unitInStock: 18,
    quantityPerUnit: "1 adet",
    category: mockCategories[4],
    description: "Video bebek monitörü",
    imageUrl: "https://picsum.photos/400/300?random=21",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Kozmetik Ürünleri
  {
    id: 22,
    productName: "Skincare Set",
    unitPrice: 400,
    unitInStock: 35,
    quantityPerUnit: "1 set",
    category: mockCategories[5],
    description: "Cilt bakım seti - 3 parça",
    imageUrl: "https://picsum.photos/400/300?random=22",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 23,
    productName: "Perfume",
    unitPrice: 800,
    unitInStock: 25,
    quantityPerUnit: "1 adet",
    category: mockCategories[5],
    description: "Erkek parfümü - 100ml",
    imageUrl: "https://picsum.photos/400/300?random=23",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Süpermarket Ürünleri
  {
    id: 24,
    productName: "Organic Honey",
    unitPrice: 80,
    unitInStock: 100,
    quantityPerUnit: "500g",
    category: mockCategories[6],
    description: "Organik çiçek balı",
    imageUrl: "https://picsum.photos/400/300?random=24",
    discount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 25,
    productName: "Olive Oil",
    unitPrice: 120,
    unitInStock: 80,
    quantityPerUnit: "1L",
    category: mockCategories[6],
    description: "Sızma zeytinyağı",
    imageUrl: "https://picsum.photos/400/300?random=25",
    discount: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Kitap & Müzik Ürünleri
  {
    id: 26,
    productName: "Programming Book",
    unitPrice: 150,
    unitInStock: 60,
    quantityPerUnit: "1 adet",
    category: mockCategories[7],
    description: "JavaScript programlama kitabı",
    imageUrl: "https://picsum.photos/400/300?random=26",
    discount: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 27,
    productName: "Bluetooth Speaker",
    unitPrice: 350,
    unitInStock: 40,
    quantityPerUnit: "1 adet",
    category: mockCategories[7],
    description: "Taşınabilir Bluetooth hoparlör",
    imageUrl: "https://picsum.photos/400/300?random=27",
    discount: 20,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Oto & Bahçe Ürünleri
  {
    id: 28,
    productName: "Car Phone Mount",
    unitPrice: 200,
    unitInStock: 50,
    quantityPerUnit: "1 adet",
    category: mockCategories[8],
    description: "Araç telefon tutucu",
    imageUrl: "https://picsum.photos/400/300?random=28",
    discount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 29,
    productName: "Garden Tools Set",
    unitPrice: 400,
    unitInStock: 25,
    quantityPerUnit: "1 set",
    category: mockCategories[8],
    description: "Bahçe aletleri seti - 5 parça",
    imageUrl: "https://picsum.photos/400/300?random=29",
    discount: 18,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Kırtasiye & Ofis Ürünleri
  {
    id: 30,
    productName: "Office Chair",
    unitPrice: 1800,
    unitInStock: 15,
    quantityPerUnit: "1 adet",
    category: mockCategories[9],
    description: "Ergonomik ofis koltuğu",
    imageUrl: "https://picsum.photos/400/300?random=30",
    discount: 25,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 31,
    productName: "Notebook Set",
    unitPrice: 50,
    unitInStock: 200,
    quantityPerUnit: "5 adet",
    category: mockCategories[9],
    description: "Spiral defter seti",
    imageUrl: "https://picsum.photos/400/300?random=31",
    discount: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Mock Campaigns
export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    title: "PREMIUM İNDİRİM GÜNLERİ",
    subtitle: "6-13 EKİM",
    description: "Premium üyelere özel indirimler",
    discount: 50,
    imageUrl: "https://picsum.photos/200/150?random=1",
    backgroundColor: "bg-gradient-to-r from-purple-600 to-purple-800",
    timeLeft: "5 gün 12 saat",
    buttonText: "Alışverişe Başla",
    buttonHref: "/products?campaign=premium",
    isActive: true,
    startDate: new Date(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: "Teknoloji Ürünlerinde",
    subtitle: "PREMIUM'A ÖZEL",
    description: "Sepette 1.000 TL'ye Varan İndirimler",
    discount: 30,
    imageUrl: "https://picsum.photos/200/150?random=2",
    backgroundColor: "bg-gradient-to-r from-blue-600 to-blue-800",
    timeLeft: "3 gün 8 saat",
    buttonText: "Teknoloji Ürünleri",
    buttonHref: "/categories/elektronik",
    isActive: true,
    startDate: new Date(),
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: "Senin İçin Seçtiklerimiz",
    subtitle: "ÖZEL FIRSATLAR",
    description: "Size özel seçilmiş ürünlerde büyük indirimler",
    discount: 25,
    imageUrl: "https://picsum.photos/200/150?random=3",
    backgroundColor: "bg-gradient-to-r from-orange-500 to-red-500",
    timeLeft: "7 gün 15 saat",
    buttonText: "Keşfet",
    buttonHref: "/products?featured=true",
    isActive: true,
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
