server:
  port: 8080

spring:
  application:
    name: ecommerce-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    driver-class-name: org.postgresql.Driver
    username: ecommerce_user
    password: ecommerce_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # JWT Configuration
  jwt:
    secret: mySecretKey
    expiration: 86400000 # 24 hours

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    com.eticaret: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
