server:
  port: 8080

spring:
  application:
    name: ecommerce-backend
  
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ecommerce_db}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:ecommerce_user}
    password: ${POSTGRES_PASSWORD:ecommerce_password}
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # H2 for development (optional)
  h2:
    console:
      enabled: false
  
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    com.eticaret: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
